version: "3"
services:
  nginx-cyan:
    image: nginx:1.16.0
    container_name: nginx-cyan
    restart: on-failure
    ports:
      - 8080:8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./sites-enabled:/etc/nginx/sites-enabled
    networks:
      - nginx-cyan-net

networks:
  nginx-cyan-net:
    driver: bridge
    external: true